server:
  port: 8001
spring:
  application:
    name: short-link-project
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      channel-topic:
        short-link-stats: 'short_link:stats-stream'
        short-link-stats-group: 'short_link:stats-stream:only-group'
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

short-link:
  domain:
    default: link.server:8001
  stats:
    locale:
      amap-key: 1b999f95a2c95b8927dbd43b18a2a1ee
  goto-domain:
    white-list:
      enable: true
      names: '4399小游戏'
      details:
        - 4399.com
        - 7k7k.com
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
